### ISSUE TITLE
Poetry install fails

### ISSUE THREAD

**Issue by boisgera** [fulcrum-so/ziggy-pydust-template#50]
Hi!

I am having this error on `poetry install`:

```
$ poetry install
Updating dependencies
Resolving dependencies... (0.7s)

No dependencies to install or update

Writing lock file

Preparing build environment with build-system requirements poetry-core, ziggy-pydust==0.19.0
zig build-lib _lib ReleaseSafe native: error: the following command failed with 1 compilation errors:
/tmp/tmp1e3fil_0/.venv/lib/python3.12/site-packages/ziglang/zig build-lib /home/boisgera/tmp/ziggy-pydust-template/src/fib.zig -lc -fallow-shlib-undefined -OReleaseSafe --cache-dir zig-cache --global-cache-dir /home/boisgera/.cache/zig --name _lib -dynamic --mod pyconf::/home/boisgera/tmp/ziggy-pydust-template/zig-cache/c/4583a83dcade58d1ac55c1d6d53b31ad/options.zig --mod pyconf0::/home/boisgera/tmp/ziggy-pydust-template/zig-cache/c/4583a83dcade58d1ac55c1d6d53b31ad/options.zig --mod pydust:pyconf:/tmp/tmp1e3fil_0/.venv/lib/python3.12/site-packages/pydust/src/pydust.zig --deps pyconf=pyconf0,pydust -I /home/boisgera/miniconda3/envs/zig/include/python3.12 --listen=- 
Build Summary: 1/4 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install generated to fibonacci/_lib.abi3.so transitive failure
   └─ zig build-lib _lib ReleaseSafe native 1 errors
/tmp/tmp1e3fil_0/.venv/lib/python3.12/site-packages/pydust/src/modules.zig:57:26: error: no field named 'ob_refcnt' in struct 'zig-cache.o.0597715355805bfa01fa5c1fa7a9164a.cimport.struct__object'
                        .ob_refcnt = 1,
                         ^~~~~~~~~
zig-cache/o/0597715355805bfa01fa5c1fa7a9164a/cimport.zig:2669:35: note: struct declared here
pub const struct__object = extern struct {
                           ~~~~~~~^~~~~~
/tmp/tmp1e3fil_0/.venv/lib/python3.12/site-packages/pydust/src/pydust.zig:60:25: note: called from here
            const obj = @call(.always_inline, moddef.init, .{}) catch return null;
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "/home/boisgera/tmp/ziggy-pydust-template/build.py", line 4, in <module>
    build()
  File "/tmp/tmp1e3fil_0/.venv/lib/python3.12/site-packages/pydust/build.py", line 22, in build
    buildzig.zig_build(["install", f"-Dpython-exe={sys.executable}", "-Doptimize=ReleaseSafe"])
  File "/tmp/tmp1e3fil_0/.venv/lib/python3.12/site-packages/pydust/buildzig.py", line 52, in zig_build
    subprocess.run(cmds, check=True)
  File "/home/boisgera/miniconda3/envs/zig/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/tmp1e3fil_0/.venv/bin/python', '-m', 'ziglang', 'build', '--build-file', PosixPath('build.zig'), 'install', '-Dpython-exe=/tmp/tmp1e3fil_0/.venv/bin/python', '-Doptimize=ReleaseSafe']' returned non-zero exit status 2.

Command ['/tmp/tmp1e3fil_0/.venv/bin/python', '/home/boisgera/tmp/ziggy-pydust-template/build.py'] errored with the following return code 1
```

Does it ring a bell?  I am working on Linux (Ubuntu 20.04.6 LTS).

Best regards,

Sébastien

**Comment by boisgera** [comment]
Just to be sure that my environment wasn't messing with the process, I have repeated it on a clean python:3.12 docker container and I have a similar error:

```
# poetry install
Creating virtualenv ziggy-pydust-template-cK1g3tkP-py3.12 in /root/.cache/pypoetry/virtualenvs
Installing dependencies from lock file

Package operations: 17 installs, 0 updates, 0 removals

  • Installing typing-extensions (4.8.0)
  • Installing annotated-types (0.6.0)
  • Installing click (8.1.7)
  • Installing mypy-extensions (1.0.0)
  • Installing packaging (23.2)
  • Installing pathspec (0.11.2)
  • Installing platformdirs (3.11.0)
  • Installing pydantic-core (2.10.1)
  • Installing black (23.12.1)
  • Installing iniconfig (2.0.0)
  • Installing pluggy (1.3.0)
  • Installing pydantic (2.4.2)
  • Installing setuptools (68.2.2)
  • Installing ziglang (0.11.0)
  • Installing pytest (7.4.4)
  • Installing ruff (0.1.14)
  • Installing ziggy-pydust (0.19.0)

Preparing build environment with build-system requirements poetry-core, ziggy-pydust==0.19.0
zig build-lib _lib ReleaseSafe native: error: the following command failed with 1 compilation errors:
/tmp/tmpbygbq671/.venv/lib/python3.12/site-packages/ziglang/zig build-lib /root/workspace/ziggy-pydust-template/src/fib.zig -lc -fallow-shlib-undefined -OReleaseSafe --cache-dir zig-cache --global-cache-dir /root/.cache/zig --name _lib -dynamic --mod pydust:pyconf:/tmp/tmpbygbq671/.venv/lib/python3.12/site-packages/pydust/src/pydust.zig --mod pyconf0::/root/workspace/ziggy-pydust-template/zig-cache/c/4583a83dcade58d1ac55c1d6d53b31ad/options.zig --mod pyconf::/root/workspace/ziggy-pydust-template/zig-cache/c/4583a83dcade58d1ac55c1d6d53b31ad/options.zig --deps pyconf=pyconf0,pydust -I /usr/local/include/python3.12 --listen=- 
Build Summary: 1/4 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install generated to fibonacci/_lib.abi3.so transitive failure
   └─ zig build-lib _lib ReleaseSafe native 1 errors
/tmp/tmpbygbq671/.venv/lib/python3.12/site-packages/pydust/src/modules.zig:57:26: error: no field named 'ob_refcnt' in struct 'zig-cache.o.cde2bc471cc259e626070385ec20efaa.cimport.struct__object'
                        .ob_refcnt = 1,
                         ^~~~~~~~~
zig-cache/o/cde2bc471cc259e626070385ec20efaa/cimport.zig:2646:35: note: struct declared here
pub const struct__object = extern struct {
                           ~~~~~~~^~~~~~
/tmp/tmpbygbq671/.venv/lib/python3.12/site-packages/pydust/src/pydust.zig:60:25: note: called from here
            const obj = @call(.always_inline, moddef.init, .{}) catch return null;
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "/root/workspace/ziggy-pydust-template/build.py", line 4, in <module>
    build()
  File "/tmp/tmpbygbq671/.venv/lib/python3.12/site-packages/pydust/build.py", line 22, in build
    buildzig.zig_build(["install", f"-Dpython-exe={sys.executable}", "-Doptimize=ReleaseSafe"])
  File "/tmp/tmpbygbq671/.venv/lib/python3.12/site-packages/pydust/buildzig.py", line 52, in zig_build
    subprocess.run(cmds, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/tmpbygbq671/.venv/bin/python', '-m', 'ziglang', 'build', '--build-file', PosixPath('build.zig'), 'install', '-Dpython-exe=/tmp/tmpbygbq671/.venv/bin/python', '-Doptimize=ReleaseSafe']' returned non-zero exit status 2.

Command ['/tmp/tmpbygbq671/.venv/bin/python', '/root/workspace/ziggy-pydust-template/build.py'] errored with the following return code 1

```

**Comment by delta003** [comment]
@boisgera let me know if https://github.com/fulcrum-so/ziggy-pydust/releases/tag/0.23.0 works, note that you should upgrade 2 versions, see https://github.com/fulcrum-so/ziggy-pydust-template/pull/24

**Comment by boisgera** [comment]
Hi @delta003!

AFAICT It doesn't work (unless my environments -- I tried 2 different settings -- are the culprits) but the error is different, see below.

BTW, I don't know if this is related, but is the reference to macosx wheels in the process normal?

If that's useful, I can try to reproduce the install steps in a similar configuration in a public github repo with github actions.

```
$ poetry install
Updating dependencies
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/ae/56/894d805c4220f21f75629d6727b78224Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/7b/0f9cc50fd6936f7b125f8682d6ece05826573fd5cbc9f4e40ddd9e2175cb/ruff-0.1.14-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl Resolving dependencies... (26.2s)

No dependencies to install or update

Writing lock file

Preparing build environment with build-system requirements poetry-core, ziggy-pydust==0.23.0
zig build-lib _lib ReleaseSafe native: error: thread 27425 panic: TODO implement readFromMemory for more types
Unable to dump stack trace: debug info stripped

zig build-lib _lib ReleaseSafe native: error: the following command terminated unexpectedly:
/tmp/tmpnf91t_95/.venv/lib/python3.12/site-packages/ziglang/zig build-lib /home/boisgera/tmp/zpt/src/fib.zig -lc -fallow-shlib-undefined -OReleaseSafe --cache-dir zig-cache --global-cache-dir /home/boisgera/.cache/zig --name _lib -dynamic --mod pyconf0::/home/boisgera/tmp/zpt/zig-cache/c/4583a83dcade58d1ac55c1d6d53b31ad/options.zig --mod pydust:pyconf:/tmp/tmpnf91t_95/.venv/lib/python3.12/site-packages/pydust/src/pydust.zig --mod pyconf::/home/boisgera/tmp/zpt/zig-cache/c/4583a83dcade58d1ac55c1d6d53b31ad/options.zig --deps pyconf=pyconf0,pydust -I /home/boisgera/tmp/zpt/.pixi/env/include/python3.12 --listen=- 
Build Summary: 1/4 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install generated to fibonacci/_lib.abi3.so transitive failure
   └─ zig build-lib _lib ReleaseSafe native failure
error: the following build command failed with exit code 1:
zig-cache/o/4682afef6e28ca19c2ab5739c1898f65/build /tmp/tmpnf91t_95/.venv/lib/python3.12/site-packages/ziglang/zig /home/boisgera/tmp/zpt zig-cache /home/boisgera/.cache/zig install -Dpython-exe=/tmp/tmpnf91t_95/.venv/bin/python -Doptimize=ReleaseSafe
Traceback (most recent call last):
  File "/home/boisgera/tmp/zpt/build.py", line 4, in <module>
    build()
  File "/tmp/tmpnf91t_95/.venv/lib/python3.12/site-packages/pydust/build.py", line 22, in build
    buildzig.zig_build(["install", f"-Dpython-exe={sys.executable}", "-Doptimize=ReleaseSafe"])
  File "/tmp/tmpnf91t_95/.venv/lib/python3.12/site-packages/pydust/buildzig.py", line 52, in zig_build
    subprocess.run(cmds, check=True)
  File "/home/boisgera/tmp/zpt/.pixi/env/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/tmpnf91t_95/.venv/bin/python', '-m', 'ziglang', 'build', '--build-file', PosixPath('build.zig'), 'install', '-Dpython-exe=/tmp/tmpnf91t_95/.venv/bin/python', '-Doptimize=ReleaseSafe']' returned non-zero exit status 1.

Command ['/tmp/tmpnf91t_95/.venv/bin/python', '/home/boisgera/tmp/zpt/build.py'] errored with the following return code 1
```

**Comment by delta003** [comment]
Sorry about that! Managed to repro it locally, fixing in https://github.com/fulcrum-so/ziggy-pydust/pull/289

We never tried it with 3.12. It should work now, will get this released ASAP

**Comment by delta003** [comment]
Let me know https://github.com/fulcrum-so/ziggy-pydust/releases/tag/0.23.1

**Comment by boisgera** [comment]
Thanks for your efforts! AFAICT I still have an error, but much later in the process (at pip install time, something related to the format of the wheel). Let me try to reproduce that in a public repo.

**Comment by boisgera** [comment]
Good news, the error was mine. Works for me, now, thank you! 👍

See: https://github.com/boisgera/ziggy-pydust-template/actions/runs/7615633172/job/20740590963

**Comment by delta003** [comment]
Nice!
